# Generated by Django 4.2.6 on 2023-10-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('geolocation_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meeting')),
                ('max_members', models.PositiveIntegerField()),
                ('views', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsdate.meeting')),
            ],
        ),
    ]
